const PROFILE = {
  name: 'Sadnan Jonayet Sajid',
  headline: 'Robotics & Embedded AI Researcher | ROS2 | SLAM | Sensor Fusion | Autonomous Navigation',
  email: 'sadnansajid355@gmail.com',
  academicEmail: '23208149@uap-bd.edu',
  phone: '+880 1604-816949',
  location: 'Dhaka, Bangladesh',
  github: 'sajid510',
  portfolio: 'sajid510.github.io',
  linkedin: 'linkedin.com/in/sadnan-sajid',
  education: {
    school: 'University of Asia Pacific (UAP), Dhaka',
    degree: 'B.Sc. Electrical & Electronic Engineering',
    years: 'Jan 2024 - Dec 2027 (Expected)',
    cgpa: '2.59 (6 F backlogs = 17cr; recovery via retakes, realistic target 3.0)',
    focus: 'Embedded Systems, Signal Processing, Control Systems, Applied AI',
  },
  researchInterests: [
    'Simultaneous Localization & Mapping (SLAM)',
    'Multi-sensor fusion (LiDAR + IMU + RGB-D)',
    'Edge AI for autonomous systems (TensorRT, YOLOv11)',
    'AI-integrated automation & agentic workflows',
  ],
  currentResearch: {
    title: 'Autonomous Mobile Robot Navigation via ROS2-Based SLAM and AI-Enhanced Decision-Making',
    team: 'Team Lead, Team Supersonic UAP (3-member robotics research group at UAP) + supervisor co-author onboarded',
    stack: 'ROS2, Nav2, SLAM Toolbox, Jetson Nano, LiDAR, Kinect RGB-D, Arduino Mega, Zenoh, Tailscale',
    status: 'Two conference papers submitted and under review: ICECE 2026 and ICCIT 2026 (results pending). Journal campaign running: 3 members × 1 paper review/week till Nov 2026 (target 10+ papers), all journal methodologies frozen before finals, hardware experiments in Dec 2026 break, manuscript written Jan-Feb 2027, journal submitted ~Mar 2027 (IROS 2027 or robotics journal). Thesis v2 (novel upgrades, same robot) due Dec 2027, journal submission ASAP in 2028.',
    paperDeadline: 'Submitted: ICECE 2026 + ICCIT 2026 (awaiting results). Next: journal ~Mar 2027',
    submissions: [
      { venue: 'ICECE 2026', title: 'A hardware-complete, local-constraint-aware, two-layer ROS 2 mobile robot architecture for supervised hospital-oriented applications in Bangladesh', status: 'submitted, results pending' },
      { venue: 'ICCIT 2026', title: 'A Privacy-Preserving Data Collection Architecture for Autonomous Robot Navigation in Bangladesh Hospitals', status: 'submitted, results pending' },
    ],
  },
  skills: [
    'ROS2, Nav2, SLAM Toolbox, Zenoh, Gazebo, TF2, RViz2, micro-ROS',
    'NVIDIA Jetson Nano, Arduino Mega, Raspberry Pi, LiDAR, Kinect RGB-D, C/C++, TensorRT, I2C/SPI/UART',
    'Python, PyTorch, OpenCV, YOLOv11, LangChain, LoRA/PEFT, RAG, ChromaDB',
    'Gemini API, Groq API, Firebase, n8n, Google Apps Script',
    'Git/GitHub, GitHub Actions, Docker, Linux/Ubuntu, LaTeX/Overleaf',
    'Project Management, Team Leadership, Stakeholder Coordination',
  ],
  experience: [
    {
      org: 'Golden Power Engineering',
      role: 'Project Manager (Assistant -> Sales Executive -> Junior Marketing Officer -> Project Manager)',
      years: 'Jan 2023 - Feb 2025',
      details: 'Managed industrial power projects (3-phase generators, substations, high-voltage distribution); launched IT product sales channel; led cross-functional teams.',
    },
    {
      org: 'Family Agribusiness (Poultry & Feed)',
      role: 'Operations Lead',
      years: 'Jun 2020 - Dec 2022',
      details: 'Ran supply chain, procurement, B2B/B2C distribution through COVID-19; restructured vendor relationships.',
    },
  ],
  achievements: [
    'Top 38 Featured Innovation (Ultron UV, Team Supersonic UAP) — BEAR Summit 2026; presented to the Honorable Prime Minister of Bangladesh, featured on national television',
    'Champion - IEEE WiE BD Summit 2024 (Robotics for Climate Change)',
    '5th Place - IEEE Region 10 Robotics Competition',
    '11th Place - 6th Kibo Robot Programming Challenge (JAXA-affiliated)',
    'Two conference papers submitted: ICECE 2026 + ICCIT 2026 (results pending)',
  ],
  leadership: [
    'Team Leader, Autonomous Robotics Research Group (Team Supersonic UAP), UAP (2024-Present)',
    'Webmaster, IEEE UAP SB WIE Affinity Group (sub-branch of IEEE UAP Student Branch)',
    'IEEE Student Member',
  ],
  languages: ['English (Professional Working)', 'Bengali (Native/Bilingual)'],
  careerGoal:
    'Fully funded MSc or Research Assistantship (2027-28 intake) in Robotics, Autonomous Systems, or Embedded AI.',
  countryTargets: ['Japan (MEXT)', 'Germany (DAAD)', 'South Korea (GKS)', 'Canada (RA)', 'USA (RA)', 'China (CSC)', 'France (Eiffel)', 'Portugal (FCT)', 'Italy', 'Malaysia (MIS)', 'Singapore (NTU)', 'Taiwan (MOE)'],
  priorityOrder: [
    'Apply Japan MEXT Apr-May 2027 (embassy track + university recommendation)',
    'Activate Canada RA professor contacts January 2027 (NSERC thesis-MASc route; Mitacs ineligible for BD)',
    'Submit Germany DAAD EPOS (Development-Related Postgraduate Courses) October 2027 for H-BRS MSc Autonomous Systems — 2028 intake. Helmut-Schmidt is social-sciences only — NEVER use.',
    'US RA route applications Sept-Dec 2027 (WPI + Oregon State only)',
    'Chevening UK October 2026 (one long-shot application)',
  ],
  criticalPath: [
    'IELTS Academic 7.0+ in August 2027 (background Oct-Apr + intensive May-Jun, book slot in June)',
    'Papers submitted: ICECE 2026 + ICCIT 2026 (track results; add acceptances to SOP/CV immediately)',
    'SOP full draft by October 2026',
    'CGPA recovery: 3.5+/semester + clear all 6 F retakes (official target 3.0, needs 3.42 avg)',
    'JLPT N5 exam Dec 6 2026 Dhaka, German A2 by Dec 2027',
    'Professor outreach full launch January 2027 (10 JP + 5 DE + 5 CA + 8-10 US)',
  ],
  operatingPrinciples: [
    'I value consistent small wins over occasional big swings.',
    'I have a 2.59 CGPA with 6 F backlogs; my strategy is retakes + achievements + papers + recommendations to compensate, so never let my low GPA demotivate the plan.',
    'Everything must run on free infrastructure.',
    'I am based in Dhaka (UTC+6), studying EEE at UAP, graduating December 2027.',
    'I want proactive nudges about deadlines and milestones, not just passive lists.',
  ],
  ieltsStrategy: 'background december 2026–Apr 2027 (30–45 min/day) + intensive last week of June-july 2027 (2hr/day) + Academic exam July 2027 target 7.0–7.5 (book British Council slot in june)',
  twoCycleStrategy: '2027 cycle = IELTS-exempt routes via MOI certificate (MEXT, CSC China, Eiffel, Portugal, Italy); 2028 cycle = IELTS-armed full round (GKS, DAAD EPOS, MIS, NTU, Taiwan MOE, Canada, USA)',
  keyDates: [
    'Spring 2026 final exams begin ~Nov 15 2026 (expected; exact routine awaited)',
    'Prep leave Nov 5-14 2026: working days full-day academic + zero project work; Fri-Sat (Nov 6-7, 13-14) full rest, no tasks',
    'Post-finals break ~1 month: full research focus (exact dates TBD - ask when the exam routine is out)',
    'Next semester class routine unknown - ask when published, then rebuild the rhythm',
    'CGPA target 3.0 official (needs 3.42 avg); 3.2 stretch; GKS 2.64 cutoff not yet met (2.59)',
    'Chevening Nov 1 2026: capped attempt, max 10 focused hours, essays before prep leave',
    'ICECE 2026 decision Nov 1 2026 (BUET); ICCIT 2026 decision TBA (Cox\'s Bazar)',
    'IELTS program: background Oct 2026-Apr 2027 (30-45m/day) + intensive May-Jun 2027 (2h/day) + Academic exam Aug 2027 target 7.0-7.5 (book slot in June); MOI certificate from UAP registrar Nov 2026 covers 2027-cycle routes',
    'Eiffel: student-side internal deadlines Oct-Nov 2026 (official Campus France close early Jan 2027, institutions-only)',
    'CSC China: watch embassy notice ~Dec 2026 (last Bangladesh window closed Jan 10); MOI conditional per program',
    'JLPT N5 exam Dec 6 2026 Dhaka (JUAAB, 4356 TK; registration open since Sep 1 - register NOW)',
  ],
};

module.exports = { PROFILE };
